version: '3.8'

services:
  admin-panel:
    build: .
    ports:
      - "3003:80"
    restart: always
    depends_on:
      - backend

  # This is a placeholder for your backend service
  # You should point this to your actual backend Docker image or build context
  backend:
    build: ../backend-panel
    env_file:
      - .env
    environment:
      - BACKEND_PORT=3001
      - PORT=3001
      - JWT_SECRET=${JWT_SECRET}
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_DB_NAME=${MONGODB_DB_NAME}
      - NODE_ENV=${NODE_ENV}
    restart: always
    ports:
      - "3001:3001"
